export const MANIFEST_WAS_SAVED = 'MANIFEST_WAS_SAVED';
export const MANIFEST_WAS_NOT_SAVED = 'MANIFEST_WAS_NOT_SAVED';
export const REQUEST_SAVE_MANIFEST = 'REQUEST_SAVE_MANIFEST';
export const MANIFEST_WAS_CREATED = 'MANIFEST_WAS_CREATED';
export const MANIFEST_WAS_NOT_CREATED = 'MANIFEST_WAS_NOT_CREATED';
export const REQUEST_CREATE_MANIFEST = 'REQUEST_CREATE_MANIFEST';