export const REQUEST_MANIFESTS = "REQUEST_MANIFESTS";
export const RECEIVE_MANIFESTS = "RECEIVE_MANIFESTS";
export const RECEIVE_MANIFESTS_FAILED = "RECEIVE_MANIFESTS_FAILED";

export const REQUEST_MANIFEST = "REQUEST_MANIFEST";
export const RECEIVE_MANIFEST = "RECEIVE_MANIFEST";
export const RECEIVE_MANIFEST_FAILED = "RECEIVE_MANIFEST_FAILED";

export const MANIFEST_WAS_SAVED = "MANIFEST_WAS_SAVED";
export const MANIFEST_WAS_NOT_SAVED = "MANIFEST_WAS_NOT_SAVED";
export const REQUEST_SAVE_MANIFEST = "REQUEST_SAVE_MANIFEST";

export const MANIFEST_WAS_CREATED = "MANIFEST_WAS_CREATED";
export const MANIFEST_WAS_NOT_CREATED = "MANIFEST_WAS_NOT_CREATED";
export const REQUEST_CREATE_MANIFEST = "REQUEST_CREATE_MANIFEST";

export const REQUEST_DELETE_MANIFEST = "REQUEST_DELETE_MANIFEST";

export const MANIFEST_WAS_DELETED = "MANIFEST_WAS_DELETED";

export const MANIFEST_WAS_NOT_DELETED = "MANIFEST_WAS_NOT_DELETED";
